apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: minikube.local:5000/dev/sample-api-svc
    jib:
      args:
        - -DskipTests
        - -Pjib

deploy:
  kubectl:
    manifests:
      - k8s/base/role.yaml
      - k8s/base/web.yaml
      - k8s/base/ingress.yaml