security.oauth2.resource:
  jwk.key-set-uri: classpath:jwks.json
  # a better solution is retrieve key set on-the-fly
  # jwk.key-set-uri: https://acnbank.auth0.com/.auth0.com/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - env
  endpoint:
    restart:
      enabled: true

spring:
  application:
    name: sample-api-svc
  cloud:
    config:
      allow-override: true
      override-system-properties: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
      url: jdbc:h2:mem:dummydb
      username: none
      password: none

