apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 8080
    name: http
  type: ClusterIP
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: web
        image: minikube.local:5000/dev/sample-api-svc
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: from_k8s_manifest_not_conjur
          - name: CUSTOM_MY_NAME
            valueFrom:
              configMapKeyRef:
                name: common
                key: custom-my-name
          - name: CUSTOM_MY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: custom-my-pass
